# Generated by Django 4.0.6 on 2022-07-15 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('auctionId', models.AutoField(primary_key=True, serialize=False)),
                ('itemName', models.CharField(max_length=100)),
                ('startTime', models.TimeField(auto_now_add=True)),
                ('endTime', models.TimeField()),
                ('startPrice', models.FloatField()),
                ('highestBid', models.FloatField(null=True)),
                ('highestBidder', models.UUIDField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='bids',
            fields=[
                ('bidID', models.AutoField(primary_key=True, serialize=False)),
                ('auctionID', models.IntegerField()),
                ('bidAmount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('userID', models.UUIDField(primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=100)),
            ],
        ),
    ]
