# Generated by Django 4.0.6 on 2022-07-15 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0003_rename_bids_bid_rename_bidders_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
