# Generated by Django 3.2.14 on 2022-07-15 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0004_auction_isactive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='endTime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='auction',
            name='highestBid',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auction',
            name='highestBidder',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auction',
            name='startTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
