# Generated by Django 3.2.14 on 2022-07-17 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0005_auto_20220716_0234'),
    ]

    operations = [
        migrations.DeleteModel(
            name='bid',
        ),
    ]
